version: '3.8'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ../src:/var/www
  database:
    image: mariadb:latest
    ports:
      - "3306"
    environment:
      - MYSQL_DATABASE=nidavellir
      - MYSQL_USER=nidavellir
      - MYSQL_PASSWORD=nidavellir
      - MYSQL_ROOT_PASSWORD=nidavellir
    volumes:
      - './docker/database/data/:/var/lib/mysql'
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ../src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"